version: '2'

volumes:
  mysql_data:
    driver: local
  www_data:
    driver: local
  backup_data:
    driver: local

networks:
  web:
    external: 
      name: web
  internal:

services:
  mysql:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - internal

  db-backup:
    image: smartpage/mariadb-backup
    environment:
      - DB_SERVER=db
      - DB_NAME=wordpress
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=XZ
      - SPLIT_DB=FALSE
      - ENABLE_ZABBIX=FALSE
    volumes:
      - backup_data:/backups
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - db
    networks:
      - internal

  wordpress:
    image: wordpress:fpm-alpine
    volumes:
      - www_data:/var/www/html/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - internal
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_TABLE_PREFIX=_wp
      - TZ="EUROPE/Berlin"
    depends_on:
      - mysql

  nginx:
    image: raulr/nginx-wordpress
    volumes:
      - www_data:/var/www/html/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN_NAME}
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - mysql
    environment:
      - POST_MAX_SIZE=128m
      - BEHIND_PROXY=true