version: '2'
volumes:
  mysql_data:
    driver: local
  www_data:
    driver: local
  backup_data:
    driver: local

networks:
  web:
    external: 
      name: web
  internal:

services:
  db:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
    command: --max_allowed_packet=64M      # Set max_allowed_packet to 256M (or any other value)
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    networks:
      - internal

  db-backup:
    image: smartpage/mariadb-backup
    environment:
      - DB_SERVER=db
      - DB_NAME=matomo
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=XZ
      - SPLIT_DB=FALSE
    volumes:
      - backup_data:/backups
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - db
    networks:
      - internal

  app:
    image: matomo:fpm
    restart: always
    links:
      - db
    volumes:
      - www_data:/var/www/html/config
    networks:
    - internal

  web:
    image: smartpage/nginx-matomo
    restart: always
    links:
      - app
    volumes_from:
      - app
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN_NAME}
      - traefik.port=80
      - VIRTUAL_HOST=${DOMAIN_NAME}
    networks:
    - internal
    - web

  cron:
    image: matomo:fpm
    restart: always
    links:
      - db
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    networks:
    - internal
